### ISSUE TITLE
Implement "clear whiteboard"

### ISSUE THREAD

**Issue by mcpower** [OldBoysofMelb/pictionary#1]
Will be useful for debugging and possibly will be used in final version.

**Comment by chaosmatic** [comment]
Yep, will be in the final version.

**Comment by chaosmatic** [comment]
[Link to commit](https://github.com/OldBoysofMelb/pictionary/commit/aa88eaa12ee4795f69db7daa43993e2ae141d3d9)

I'm just continuing the use of the pattern:
1. Listen for event, then fire off socket message.
2. call function to actually do the thing
3. Server receives and broadcasts the message
4. Other clients receive message and actually do the thing

One question is, should the canvas context be global, or passed into the functions that draw or clear it?
