### ISSUE TITLE
Drawing a long line lags client

### ISSUE THREAD

**Issue by Enzime** [OldBoysofMelb/pictionary#4]
When you draw a long line, it begins to lag the client.

Socket.io appears to be the cause of this issue (when I remove the code to send points over the network the client no longer lags)

**Comment by chaosmatic** [comment]
How long of a line?

**Comment by Enzime** [comment]
Roughly 1000 points, can be a lot shorter or longer before it starts lagging, depends on how you draw the line it seems.

**Comment by chaosmatic** [comment]
I don't seem to have this issue on chrome.

**Comment by chaosmatic** [comment]
I believe it's due to speed not length. I can get polygon like circles by point 80
![screenshot - 130616 - 22 18 38](https://cloud.githubusercontent.com/assets/10492681/16007398/7dd892c0-31b5-11e6-981f-f5305c98391b.png)

**Comment by chaosmatic** [comment]
RHS 1k line, LHS 80pt line
Hopefully same speed of circling, but who knows, my wrist might have gotten tired.
![screenshot - 130616 - 22 23 36](https://cloud.githubusercontent.com/assets/1475175/16007410/962cbfcc-31b5-11e6-92a5-bb39ac36356e.png)
